name: CFN Test

on:
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'eu-east-1'

jobs:
  cluster:
    name: Deploy stack to AWS
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ${{ github.event.inputs.region}}

    - name: Deploy CFN Stack
      id: TestStack
      uses: aws-actions/aws-cloudformation-github-deploy@master
      with:
        name: TestStack
        template: cfn/LambdaTemplate.yaml
        no-fail-on-empty-changeset: "1"
